### ISSUE TITLE
Doesn't work when Prettier is only installed globally

### ISSUE THREAD

**Issue by aharris88** [kentcdodds/prettier-eslint-cli#3]
I have `prettier` and `prettier-eslint-cli` installed globally because I want to use it in any JavaScript project with vim.

When I format a file, I get the text of the file replaced with this:

```
prettier-eslint-cli error: There was a problem trying to format the stdin text Error: Cannot find module '../../../../../../path/to/current/project/node_modules/prettier'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at prettify (/usr/local/lib/node_modules/prettier-eslint-cli/node_modules/prettier-eslint/dist/index.js:79:16)
    at format (/usr/local/lib/node_modules/prettier-eslint-cli/node_modules/prettier-eslint/dist/index.js:66:18)
    at _callee2$ (/usr/local/lib/node_modules/prettier-eslint-cli/dist/format-files.js:77:54)
    at tryCatch (/usr/local/lib/node_modules/prettier-eslint-cli/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/prettier-eslint-cli/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/prettier-eslint-cli/node_modules/regenerator-runtime/runtime.js:116:21)
```

But when I install `prettier` locally in the project, it works. I feel like it should work either way.

**Comment by kentcdodds** [comment]
Gotcha. Actually, the core package just improved it's module path identification strategy so I'm thinking that all we need to do is remove the default value (in parser.js) for those two options and we should be alright. Will remove the `default` in the help message, but that's probably OK.

**Comment by kentcdodds** [comment]
Would you like to make that contribution? And test it locally to make sure it works?

**Comment by aharris88** [comment]
Yeah, I'll give it a shot.

**Comment by kentcdodds** [comment]
Awesome! I look forward to seeing the pull request!
